apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-shell
  namespace: default
spec:
  selector:
   matchLabels:
    run: test
  process:
    matchPaths:
    - path: /bin/sh
  action: Block